# Generated by Django 4.2.7 on 2023-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='map',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=256, null=True),
        ),
    ]
